language: node_js
os: linux
dist: xenial
node_js:
- 'lts/*'
branches:
  only:
    - dev
cache:
  directories:
    - node_modules
before_install:
  - yarn install
script:
  - yarn gulp build
deploy:
  strategy: git
  provider: pages
  local_dir: ./public
  target_branch: master
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: dev
