language: node_js
node_js:
- 'lts/*'
branches:
  only:
    - dev
cache:
  directories:
    - node_modules
before_install:
  - yarn install
script:
  - yarn gulp build
deploy:
  provider: pages
  local-dir: ./public
  target-branch: master
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: dev
